ALPACA_API_KEY = "REMOVED_CREDENTIAL"
ALPACA_SECRET_KEY = "REMOVED_CREDENTIAL"
ALPACA_BASE_URL = "https://data.alpaca.markets"



EMA_FAST = 9
EMA_SLOW = 21
EMA_TREND = 50

RSI_PERIOD = 14
ATR_PERIOD = 14

DTE_RANGE = (30, 45)
DELTA_RANGE = (0.60, 0.75)