WATCHLIST = [
    "SPY", "QQQ",
    "AAPL", "MSFT", "GOOGL", "AMZN", "NVDA", "META", "TSLA", "APP",
    "AVGO", "ADBE", "CRM", "ORCL", "CSCO", "INTC", "AMD", "QCOM",
    "TXN", "INTU", "NOW", "AMAT", "MU", "LRCX", "KLAC", "SNPS", "CDNS",
    "PANW", "CRWD", "DDOG", "NET", "ZS", "SNOW", "PLTR", "TEAM",
    "WDAY", "ADSK", "UBER", "ABNB", "CRCL", "ZM", "RBLX", "ONON",
    "COIN", "PYPL", "MSTR", "APLD", "BIDU", "BABA", "FUTU", "SMCI",
    "NFLX", "DIS", "CMCSA", "T", "VZ", "TMUS", "TTD", "BULL", "HIMS", "CELH",
    "CMG", "MCD", "SBUX", "NKE", "LULU", "LOW", "HD", "TGT", "WMT", "COST",
    "PG", "KO", "PEP", "PM",'HOOD',
    "UNH", "JNJ", "LLY", "ABBV", "MRK", "TMO", "ABT", "PFE", "AMGN", "GILD",
    "REGN", "VRTX", "ISRG", "BSX", "SYK", "MDT", "ZTS",
    "JPM", "V", "MA", "BAC", "WFC", "MS", "GS", "BLK", "C", "SCHW", "AXP",
    "COF", "BX", "KKR",
    "XOM", "CVX", "COP", "SLB", "EOG", "OXY",
    "CAT", "BA", "HON", "UNP", "RTX", "GE", "LMT", "DE", "UPS", "FDX", "UPST",
    "ETN", "GD", "NOC", "CSX",
    "LIN", "APD", "SHW", "NEM", "FCX", "NUE",
    "AMT", "PLD", "EQIX", "PSA", "O",
    "NEE", "DUK", "SO",
    "TSM", "ASML", "TER", "ENTG", "MPWR",
    "RIVN", "ENPH", "FSLR",
]